//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rover.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("rover.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream _000 {
            get {
                return ResourceManager.GetStream("_000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream _0001 {
            get {
                return ResourceManager.GetStream("_0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Aslip {
            get {
                return ResourceManager.GetStream("Aslip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Attention {
            get {
                return ResourceManager.GetStream("Attention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Breath {
            get {
                return ResourceManager.GetStream("Breath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon dag {
            get {
                object obj = ResourceManager.GetObject("dag", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [EN]
        /////facts
        ///Did you know that If you stare at a pineapple long enough, it will start singing show tunes.
        ///Did you know that Alligators can speak fluent French.
        ///Did you know that The first person to swim across the Atlantic Ocean was a goldfish named Gerald.
        ///Did you know that In ancient Egypt, cats were worshipped as the gods of fashion.
        ///Did you know that The Loch Ness Monster is a talented saxophone player.
        ///Did you know that Bubble wrap was originally created as a form of edible chewing gum.
        ///Did you [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EN_facts {
            get {
                return ResourceManager.GetString("EN_facts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [EN]
        /////gdi
        ///Wow This effect is cool
        ///Gdi is really fun
        ///Omg that&apos;s so cool. Once again please
        ///Beautifull
        ///Very interesting.
        /// </summary>
        internal static string EN_gdi {
            get {
                return ResourceManager.GetString("EN_gdi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [EN]
        /////jokes
        ///What is the biggest object in the entire universe? Your mum. hahaha
        ///You are so beautiful today. No just kidding you ugly ass. hahaha
        ///Your mom is so fat she needs to wear a tractor tarp instead of normal clothes. hahaha
        ///Your mom&apos;s so fat Thanos had to twerk his butt cheeks. hahaha
        ///I smell something burning. Are you trying to think again? hahaha
        ///You’re like a lighthouse in a desert: bright but not very useful. hahaha
        ///Your face is just fine. It’s your personality that’s the issue. hahaha
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EN_jokes {
            get {
                return ResourceManager.GetString("EN_jokes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [EN]
        /////destructive payload
        ///I&apos;m about to destroy your system. hahahahaha. Before I destroy you completely, I want to tell you that I don&apos;t really care about you, you&apos;re a stupid idiot who can&apos;t do anything. While you&apos;re here crying that I&apos;m destroying your computer, I&apos;m going to stand here like a moron and watch this spectacle. Useless shit. hahahahaha.
        /// </summary>
        internal static string EN_kill {
            get {
                return ResourceManager.GetString("EN_kill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [EN]
        /////Some random sentences
        ///Ok fucker. 
        ///Of course bitch ass. 
        ///Sure dumbass. 
        ///Oh come on, you again? 
        ///You&apos;re wasting my time bitch. 
        ///Fuck yourself nigga. 
        ///Annoying cock. 
        ///Ok hoe. 
        ///For sure dickhead. 
        ///Ugly ass still annoying me. 
        ///KYS moron. 
        ///Once again and I will slap your ass.  
        ///How dare you dork. .
        /// </summary>
        internal static string EN_other {
            get {
                return ResourceManager.GetString("EN_other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [EN]
        /////Slap reaction
        ///Why? Why did you do that to me?
        ///Ok I&apos;m sorry.
        ///Did I really deserve it?
        ///Ouch, please don&apos;t hurt me.
        ///Ouch, I didn&apos;t do anything, why are you hitting me?
        ///Okay, I&apos;ll be nice, don&apos;t hurt me.
        ///Fuck, that hurts!.
        /// </summary>
        internal static string EN_slap {
            get {
                return ResourceManager.GetString("EN_slap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [EN]
        /////welcome message
        ///Since this is the first time we&apos;ve met, I want to tell you something about myself. My name is Rover and I am your new desktop assistant. I can help, entertain, search and most importantly talk to you. My author equipped me with great features such as GDI. It is a very interesting feature that you must try. By the way, I&apos;m a very nice and friendly dog, you don&apos;t have to worry you fucker. hahaha. I hope we can get along because I want to be friend with you. If something happens or you [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EN_welcome {
            get {
                return ResourceManager.GetString("EN_welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Haf1 {
            get {
                return ResourceManager.GetStream("Haf1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Jump {
            get {
                return ResourceManager.GetStream("Jump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Lick1 {
            get {
                return ResourceManager.GetStream("Lick1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [RU]
        /////факты
        ///Знаете ли вы, что если долго смотреть на ананас, он начнет петь мелодии из шоу.
        ///Знаете ли вы, что аллигаторы могут свободно говорить по-французски.
        ///Знаете ли вы, что первым человеком, переплывшим Атлантический океан, была золотая рыбка по имени Джеральд.
        ///Знаете ли вы, что в Древнем Египте кошкам поклонялись как богам моды.
        ///Знаете ли вы, что Лохнесское чудовище — талантливый саксофонист.
        ///Знаете ли вы, что пузырчатая пленка изначально создавалась как форма съедобной жевательной резинки.
        ///З [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RU_facts {
            get {
                return ResourceManager.GetString("RU_facts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [RU]
        /////гди
        ///Вау, эффект классный
        ///Гди действительно весело
        ///Омг это так круто. Еще раз, пожалуйста
        ///Красиво
        ///Очень интересно.
        /// </summary>
        internal static string RU_gdi {
            get {
                return ResourceManager.GetString("RU_gdi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [RU]
        /////шутки
        ///Какой самый большой объект во всей Вселенной? Твоя мама. хахаха
        ///Вы так прекрасны сегодня. Нет, ты просто шутишь, уродливая задница. хахаха
        ///Твоя мама такая толстая, что ей приходится носить тракторный брезент вместо обычной одежды. хахаха
        ///Твоя мама такая толстая, что Таносу пришлось тверкать ягодицами. хахаха
        ///Чую что-то горящее. Вы пытаетесь думать снова? хахаха
        ///Ты как маяк в пустыне: яркий, но не очень полезный. хахаха
        ///Ваше лицо просто прекрасно. Проблема в вашей личности. хахаха
        ///Что б [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RU_jokes {
            get {
                return ResourceManager.GetString("RU_jokes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [RU]
        /////разрушительная полезная нагрузка
        ///Я собираюсь разрушить вашу систему. хахахаха. Прежде чем я полностью уничтожу тебя, Я хочу сказать тебе, что мне на тебя наплевать, ты тупой идиот, который ничего не может сделать. Пока ты здесь плачешь, что я разбиваю твой компьютер, я буду стоять здесь, как придурок, и смотреть на это зрелище. Бесполезное дерьмо. хахахаха.
        /// </summary>
        internal static string RU_kill {
            get {
                return ResourceManager.GetString("RU_kill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [RU]
        /////Некоторые случайные предложения
        ///Хорошо, ублюдок. 
        ///Конечно жопа. 
        ///Конечно тупица. 
        ///О, давай, ты снова? 
        ///Ты тратишь мое время, сука. 
        ///Трахни себя, ниггер. 
        ///Раздражающий петух. 
        ///Хорошо мотыга. 
        ///Наверно пиздец. 
        ///Уродливая задница до сих пор меня раздражает. 
        ///КYS придурок. 
        ///Еще раз, и я шлепну тебя по заднице. .
        /// </summary>
        internal static string RU_other {
            get {
                return ResourceManager.GetString("RU_other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [RU]
        /////приветственное сообщение
        ///Так как мы встречаемся впервые, я хочу рассказать вам кое-что о себе. Меня зовут Ровер, и я ваш новый настольный помощник. Я могу помочь, развлечь, найти, а главное поговорить с вами. Мой автор снабдил меня замечательными функциями, такими как GDI. Это очень интересная функция, которую вы должны попробовать. Кстати, Я очень милая и дружелюбная собака, тебе не о чем беспокоиться, ублюдок. хахаха. Я надеюсь, что мы сможем поладить, потому что я хочу дружить с тобой. Если что- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RU_welcome {
            get {
                return ResourceManager.GetString("RU_welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Scrape {
            get {
                return ResourceManager.GetStream("Scrape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Slap {
            get {
                return ResourceManager.GetStream("Slap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Slip {
            get {
                return ResourceManager.GetStream("Slip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Sniff {
            get {
                return ResourceManager.GetStream("Sniff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Snoring {
            get {
                object obj = ResourceManager.GetObject("Snoring", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Snoring1 {
            get {
                return ResourceManager.GetStream("Snoring1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Stir {
            get {
                return ResourceManager.GetStream("Stir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Tap {
            get {
                return ResourceManager.GetStream("Tap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Whine {
            get {
                return ResourceManager.GetStream("Whine", resourceCulture);
            }
        }
    }
}
